export default [
  'Advice on funding',
  'Bootstrapping',
  'Building a team',
  'Content marketing',
  'Conversion rate optimization',
  'Copywriting',
  'No-code',
  'Link building',
  'Mindset coaching',
  'Marketing automation',
  'Idea validation',
  'Growth marketing',
  'Go to market strategy',
  'Email marketing',
  'Design / UX',
  'Data science',
  'Customer success',
  'Product marketing',
  'Product market fit',
  'Product management',
  'Product launches',
  'Product analytics',
  'Pricing strategy',
  'PPC strategies',
  'Productized services',
  'Public relations',
  'User research',
  'Venting frustration',
  'Technology and tools',
  'Social media',
  'SEO',
  'Sales',
  'Remote work',
];

// export default [
//   {
//     title: 'Abuse',
//     slug: 'abuse',
//     url: 'https://www.therapyden.com/specialties/abuse',
//   },
//   {
//     title: 'Acceptance and Commitment Therapy (ACT)',
//     slug: 'acceptance-and-commitment-therapy-act',
//     url: 'https://www.therapyden.com/specialties/acceptance-and-commitment-therapy-act',
//   },
//   {
//     title: 'Addiction Counseling',
//     slug: 'addiction-counseling',
//     url: 'https://www.therapyden.com/specialties/addiction-counseling',
//   },
//   {
//     title: 'ADHD',
//     slug: 'adhd',
//     url: 'https://www.therapyden.com/specialties/adhd',
//   },
//   {
//     title: 'Adjustment Disorder',
//     slug: 'adjustment-disorder',
//     url: 'https://www.therapyden.com/specialties/adjustment-disorder',
//   },
//   {
//     title: 'Adoption Issues',
//     slug: 'adoption-issues',
//     url: 'https://www.therapyden.com/specialties/adoption-issues',
//   },
//   {
//     title: 'Aging Concerns',
//     slug: 'aging-concerns',
//     url: 'https://www.therapyden.com/specialties/aging-concerns',
//   },
//   {
//     title: 'Alcohol Abuse and Alcohol Dependence',
//     slug: 'alcohol-abuse-and-alcohol-dependence',
//     url: 'https://www.therapyden.com/specialties/alcohol-abuse-and-alcohol-dependence',
//   },
//   {
//     title: "Alzheimer's",
//     slug: 'alzheimers',
//     url: 'https://www.therapyden.com/specialties/alzheimers',
//   },
//   {
//     title: 'Anger Issues',
//     slug: 'anger-issues',
//     url: 'https://www.therapyden.com/specialties/anger-issues',
//   },
//   {
//     title: 'Anger Management Therapy',
//     slug: 'anger-management-therapy',
//     url: 'https://www.therapyden.com/specialties/anger-management-therapy',
//   },
//   {
//     title: 'Anxiety',
//     slug: 'anxiety',
//     url: 'https://www.therapyden.com/specialties/anxiety',
//   },
//   {
//     title: 'Art Therapy',
//     slug: 'art-therapy',
//     url: 'https://www.therapyden.com/specialties/art-therapy',
//   },
//   {
//     title: 'Attachment Theory',
//     slug: 'attachment-theory',
//     url: 'https://www.therapyden.com/specialties/attachment-theory',
//   },
//   {
//     title: 'Burnout',
//     slug: 'burnout',
//     url: 'https://www.therapyden.com/specialties/burnout',
//   },
//   {
//     title: 'Coparenting',
//     slug: 'coparenting',
//     url: 'https://www.therapyden.com/specialties/coparenting',
//   },
//   {
//     title: 'Autism Spectrum Disorder',
//     slug: 'autism',
//     url: 'https://www.therapyden.com/specialties/autism',
//   },
//   {
//     title: 'Bipolar',
//     slug: 'bipolar',
//     url: 'https://www.therapyden.com/specialties/bipolar',
//   },
//   {
//     title: 'Body Image Issues',
//     slug: 'body-image-issues',
//     url: 'https://www.therapyden.com/specialties/body-image-issues',
//   },
//   {
//     title: 'Cancer',
//     slug: 'cancer',
//     url: 'https://www.therapyden.com/specialties/cancer',
//   },
//   {
//     title: 'Career Counseling',
//     slug: 'career-counseling',
//     url: 'https://www.therapyden.com/specialties/career-counseling',
//   },
//   {
//     title: 'Child Issues',
//     slug: 'child-issues',
//     url: 'https://www.therapyden.com/specialties/child-issues',
//   },
//   {
//     title: 'Chronic Pain or Illness',
//     slug: 'chronic-pain-or-illness',
//     url: 'https://www.therapyden.com/specialties/chronic-pain-or-illness',
//   },
//   {
//     title: 'Codependency',
//     slug: 'codependency',
//     url: 'https://www.therapyden.com/specialties/codependency',
//   },
//   {
//     title: 'Cultural and Systemic Oppression',
//     slug: 'cultural-and-systemic-oppression',
//     url: 'https://www.therapyden.com/specialties/cultural-and-systemic-oppression',
//   },
//   {
//     title: 'Depression',
//     slug: 'depression',
//     url: 'https://www.therapyden.com/specialties/depression',
//   },
//   {
//     title: 'Dissociative Disorders',
//     slug: 'dissociative-disorders',
//     url: 'https://www.therapyden.com/specialties/dissociative-disorders',
//   },
//   {
//     title: 'Divorce',
//     slug: 'divorce',
//     url: 'https://www.therapyden.com/specialties/divorce',
//   },
//   {
//     title: 'Domestic Violence or Intimate Partner Violence',
//     slug: 'domestic-violence-and-intimate-partner-violence',
//     url: 'https://www.therapyden.com/specialties/domestic-violence-and-intimate-partner-violence',
//   },
//   {
//     title: 'Drug Dependence / Abuse / Addiction',
//     slug: 'drug-dependence-abuse-addiction',
//     url: 'https://www.therapyden.com/specialties/drug-dependence-abuse-addiction',
//   },
//   {
//     title: 'Eating Disorders',
//     slug: 'eating-disorders',
//     url: 'https://www.therapyden.com/specialties/eating-disorders',
//   },
//   {
//     title: 'Exposure Therapy',
//     slug: 'exposure-therapy',
//     url: 'https://www.therapyden.com/specialties/exposure-therapy',
//   },
//   {
//     title: 'Family Caregiving Stress',
//     slug: 'family-caregiving',
//     url: 'https://www.therapyden.com/specialties/family-caregiving',
//   },
//   {
//     title: 'Family Conflict',
//     slug: 'family-conflict',
//     url: 'https://www.therapyden.com/specialties/family-conflict',
//   },
//   {
//     title: 'Gambling Addiction',
//     slug: 'gambling-addiction',
//     url: 'https://www.therapyden.com/specialties/gambling-addiction',
//   },
//   {
//     title: 'Gender Identity',
//     slug: 'gender-identity',
//     url: 'https://www.therapyden.com/specialties/gender-identity',
//   },
//   {
//     title: 'Historical/ Intergenerational Trauma',
//     slug: 'historical-trauma',
//     url: 'https://www.therapyden.com/specialties/historical-trauma',
//   },
//   {
//     title: 'Immigration/Acculturation',
//     slug: 'immigration-acculturation',
//     url: 'https://www.therapyden.com/specialties/immigration-acculturation',
//   },
//   {
//     title: 'Infertility',
//     slug: 'infertility',
//     url: 'https://www.therapyden.com/specialties/infertility',
//   },
//   {
//     title: 'Insomnia',
//     slug: 'insomnia',
//     url: 'https://www.therapyden.com/specialties/insomnia',
//   },
//   {
//     title: 'Intellectual Disability',
//     slug: 'intellectual-disability',
//     url: 'https://www.therapyden.com/specialties/intellectual-disability',
//   },
//   {
//     title: 'Internet Addiction',
//     slug: 'internet-addiction',
//     url: 'https://www.therapyden.com/specialties/internet-addiction',
//   },
//   {
//     title: 'Learning Disorders',
//     slug: 'learning-disorders',
//     url: 'https://www.therapyden.com/specialties/learning-disorders',
//   },
//   {
//     title: 'LGBTQ Issues',
//     slug: 'lgbtq-issues',
//     url: 'https://www.therapyden.com/specialties/lgbtq-issues',
//   },
//   {
//     title: 'Life transitions',
//     slug: 'life-transitions',
//     url: 'https://www.therapyden.com/specialties/life-transitions',
//   },
//   {
//     title: 'Grief or Loss',
//     slug: 'grief-or-loss',
//     url: 'https://www.therapyden.com/specialties/grief-or-loss',
//   },
//   {
//     title: 'Medication Management',
//     slug: 'medication-management',
//     url: 'https://www.therapyden.com/specialties/medication-management',
//   },
//   {
//     title: "Men's Issues",
//     slug: 'mens-issues',
//     url: 'https://www.therapyden.com/specialties/mens-issues',
//   },
//   {
//     title: 'Emotional Eating',
//     slug: 'emotional-eating',
//     url: 'https://www.therapyden.com/specialties/emotional-eating',
//   },
//   {
//     title: 'Obsessive Compulsive Disorder (OCD)',
//     slug: 'obsessive-compulsive-disorder-ocd',
//     url: 'https://www.therapyden.com/specialties/obsessive-compulsive-disorder-ocd',
//   },
//   {
//     title: 'Oppositional Defiant Disorder (ODD)',
//     slug: 'oppositional-defiant-disorder-odd',
//     url: 'https://www.therapyden.com/specialties/oppositional-defiant-disorder-odd',
//   },
//   {
//     title: 'Panic',
//     slug: 'panic',
//     url: 'https://www.therapyden.com/specialties/panic',
//   },
//   {
//     title: 'Parenting',
//     slug: 'parenting',
//     url: 'https://www.therapyden.com/specialties/parenting',
//   },
//   {
//     title: 'Personal Growth',
//     slug: 'personal-growth',
//     url: 'https://www.therapyden.com/specialties/personal-growth',
//   },
//   {
//     title: 'Personality Disorders',
//     slug: 'personality-disorders',
//     url: 'https://www.therapyden.com/specialties/personality-disorders',
//   },
//   {
//     title: 'Political Climate',
//     slug: 'political-climate',
//     url: 'https://www.therapyden.com/specialties/political-climate',
//   },
//   {
//     title: 'Polyamorous and Open Relationships',
//     slug: 'polyamorous-and-open-relationships',
//     url: 'https://www.therapyden.com/specialties/polyamorous-and-open-relationships',
//   },
//   {
//     title: 'Post Traumatic Stress Disorder (PTSD)',
//     slug: 'post-traumatic-stress-disorder-ptsd',
//     url: 'https://www.therapyden.com/specialties/post-traumatic-stress-disorder-ptsd',
//   },
//   {
//     title: 'Pregnancy and Postpartum',
//     slug: 'pregnancy-postpartum',
//     url: 'https://www.therapyden.com/specialties/pregnancy-postpartum',
//   },
//   {
//     title: 'Psychosis and Schizophrenia',
//     slug: 'psychosis-schizophrenia',
//     url: 'https://www.therapyden.com/specialties/psychosis-schizophrenia',
//   },
//   {
//     title: 'Racial Identity',
//     slug: 'racial-identity',
//     url: 'https://www.therapyden.com/specialties/racial-identity',
//   },
//   {
//     title: 'Relationship / Marriage Issues',
//     slug: 'relationship-marriage-issues',
//     url: 'https://www.therapyden.com/specialties/relationship-marriage-issues',
//   },
//   {
//     title: 'Self-Esteem',
//     slug: 'self-esteem',
//     url: 'https://www.therapyden.com/specialties/self-esteem',
//   },
//   {
//     title: 'Self-Harm',
//     slug: 'self-harm',
//     url: 'https://www.therapyden.com/specialties/self-harm',
//   },
//   {
//     title: 'Sexual Abuse or Assault',
//     slug: 'sexual-abuse-assault',
//     url: 'https://www.therapyden.com/specialties/sexual-abuse-assault',
//   },
//   {
//     title: 'Sexual Addiction',
//     slug: 'sexual-addiction',
//     url: 'https://www.therapyden.com/specialties/sexual-addiction',
//   },
//   {
//     title: 'Sexual Identity',
//     slug: 'sexual-identity',
//     url: 'https://www.therapyden.com/specialties/sexual-identity',
//   },
//   {
//     title: 'Sexual Problems',
//     slug: 'sexual-problems',
//     url: 'https://www.therapyden.com/specialties/sexual-problems',
//   },
//   {
//     title: 'Social Phobia',
//     slug: 'social-phobia',
//     url: 'https://www.therapyden.com/specialties/social-phobia',
//   },
//   {
//     title: 'Spirituality',
//     slug: 'spirituality',
//     url: 'https://www.therapyden.com/specialties/spirituality',
//   },
//   {
//     title: 'Stress',
//     slug: 'stress',
//     url: 'https://www.therapyden.com/specialties/stress',
//   },
//   {
//     title: 'Suicidal Thoughts',
//     slug: 'suicidal-thoughts',
//     url: 'https://www.therapyden.com/specialties/suicidal-thoughts',
//   },
//   {
//     title: 'Tourette Syndrome',
//     slug: 'tourette-syndrome',
//     url: 'https://www.therapyden.com/specialties/tourette-syndrome',
//   },
//   {
//     title: 'Veterans/Military Service',
//     slug: 'veterans-military-service',
//     url: 'https://www.therapyden.com/specialties/veterans-military-service',
//   },
//   {
//     title: 'White Privilege/Fragility',
//     slug: 'white-privilege',
//     url: 'https://www.therapyden.com/specialties/white-privilege',
//   },
//   {
//     title: "Women's Issues",
//     slug: 'womens-issues',
//     url: 'https://www.therapyden.com/specialties/womens-issues',
//   },
//   {
//     title: 'Compassion Fatigue',
//     slug: 'compassion-fatigue',
//     url: 'https://www.therapyden.com/specialties/compassion-fatigue',
//   },
//   {
//     title: 'Biofeedback',
//     slug: 'biofeedback',
//     url: 'https://www.therapyden.com/specialties/biofeedback',
//   },
//   {
//     title: 'Coaching',
//     slug: 'coaching',
//     url: 'https://www.therapyden.com/specialties/coaching',
//   },
//   {
//     title: 'Cognitive Behavioral Therapy (CBT)',
//     slug: 'cognitive-behavioral-therapy-cbt',
//     url: 'https://www.therapyden.com/specialties/cognitive-behavioral-therapy-cbt',
//   },
//   {
//     title: 'Collaborative Couple Therapy',
//     slug: 'collaborative-couple-therapy',
//     url: 'https://www.therapyden.com/specialties/collaborative-couple-therapy',
//   },
//   {
//     title: 'Contemplative Therapy',
//     slug: 'contemplative-therapy',
//     url: 'https://www.therapyden.com/specialties/contemplative-therapy',
//   },
//   {
//     title: 'Couples Counseling',
//     slug: 'couples-counseling',
//     url: 'https://www.therapyden.com/specialties/couples-counseling',
//   },
//   {
//     title: 'Culturally Sensitive Therapy',
//     slug: 'culturally-sensitive-therapy',
//     url: 'https://www.therapyden.com/specialties/culturally-sensitive-therapy',
//   },
//   {
//     title: 'Dance / Movement Therapy',
//     slug: 'dance-movement-therapy',
//     url: 'https://www.therapyden.com/specialties/dance-movement-therapy',
//   },
//   {
//     title: 'Depth Therapy',
//     slug: 'depth-therapy',
//     url: 'https://www.therapyden.com/specialties/depth-therapy',
//   },
//   {
//     title: 'Dialectical Behavior Therapy (DBT)',
//     slug: 'dialectical-behavior-therapy-dbt',
//     url: 'https://www.therapyden.com/specialties/dialectical-behavior-therapy-dbt',
//   },
//   {
//     title: 'Eclectic Therapy',
//     slug: 'eclectic-therapy',
//     url: 'https://www.therapyden.com/specialties/eclectic-therapy',
//   },
//   {
//     title: 'EcoTherapy',
//     slug: 'ecotherapy',
//     url: 'https://www.therapyden.com/specialties/ecotherapy',
//   },
//   {
//     title: 'EMDR',
//     slug: 'emdr',
//     url: 'https://www.therapyden.com/specialties/emdr',
//   },
//   {
//     title: 'Emotionally Focused Therapy',
//     slug: 'emotionally-focused-therapy',
//     url: 'https://www.therapyden.com/specialties/emotionally-focused-therapy',
//   },
//   {
//     title: 'Energy Psychology',
//     slug: 'energy-psychology',
//     url: 'https://www.therapyden.com/specialties/energy-psychology',
//   },
//   {
//     title: 'Equine Assisted Psychotherapy (EAP)',
//     slug: 'equine-assisted-psychotherapy-eap',
//     url: 'https://www.therapyden.com/specialties/equine-assisted-psychotherapy-eap',
//   },
//   {
//     title: 'Existential Therapy',
//     slug: 'existential-therapy',
//     url: 'https://www.therapyden.com/specialties/existential-therapy',
//   },
//   {
//     title: 'Experiential Therapy',
//     slug: 'experiential-therapy',
//     url: 'https://www.therapyden.com/specialties/experiential-therapy',
//   },
//   {
//     title: 'Expressive Art Therapy',
//     slug: 'expressive-art-therapy',
//     url: 'https://www.therapyden.com/specialties/expressive-art-therapy',
//   },
//   {
//     title: 'Family Systems',
//     slug: 'family-systems',
//     url: 'https://www.therapyden.com/specialties/family-systems',
//   },
//   {
//     title: 'Family Therapy',
//     slug: 'family-therapy',
//     url: 'https://www.therapyden.com/specialties/family-therapy',
//   },
//   {
//     title: 'Feminist Therapy',
//     slug: 'feminist-therapy',
//     url: 'https://www.therapyden.com/specialties/feminist-therapy',
//   },
//   {
//     title: 'Gestalt Therapy',
//     slug: 'gestalt-therapy',
//     url: 'https://www.therapyden.com/specialties/gestalt-therapy',
//   },
// ];
